//! Screen manifest generation for HERDR agent detection.
//!
//! Screen manifests tell HERDR how to detect agent state from terminal
//! output. These TOML files define rules that match text patterns in
//! the pane's bottom buffer.
//!
//! HERDR evaluates manifests against the live bottom-buffer snapshot.
//! Each rule has a `state` (working/idle/blocked), match patterns,
//! and optional region constraints.

/// A single detection rule in a screen manifest.
pub struct DetectionRule {
    /// Agent state this rule asserts.
    pub state: AgentState,
    /// Text patterns that must all match (AND logic).
    pub patterns: Vec<String>,
    /// Optional description for documentation.
    pub description: String,
}

/// Screen manifest for an agent. Generates the TOML that HERDR
/// uses for screen-based detection.
pub struct ScreenManifest {
    /// Agent name (e.g. "jcode", "forgecode").
    pub agent: String,
    /// Manifest version.
    pub version: String,
    /// Detection rules evaluated in order.
    pub rules: Vec<DetectionRule>,
}

impl ScreenManifest {
    /// Generate the TOML manifest string.
    pub fn to_toml(&self) -> String {
        let mut out = format!(
            "# HERDR screen manifest for {}\n\
             # Auto-generated by jcode-herdr\n\
             agent = \"{}\"\n\
             version = \"{}\"\n\n",
            self.agent, self.agent, self.version
        );

        for (i, rule) in self.rules.iter().enumerate() {
            out.push_str(&format!(
                "[[rules]]\n\
                 # Rule {}: {}\n\
                 state = \"{}\"\n",
                i + 1,
                rule.description,
                rule.state.as_str(),
            ));
            // Use TOML inline array to avoid duplicate keys
            out.push_str("patterns = [");
            for (j, pattern) in rule.patterns.iter().enumerate() {
                if j > 0 {
                    out.push_str(", ");
                }
                out.push_str(&format!("{:?}", pattern));
            }
            out.push_str("]\n\n");
        }

        out
    }
}

use crate::state::AgentState;

/// Build the jcode screen manifest.
pub fn jcode_manifest() -> ScreenManifest {
    ScreenManifest {
        agent: "jcode".to_string(),
        version: "1".to_string(),
        rules: vec![
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["●".to_string()],
                description: "jcode spinner active (working)".to_string(),
            },
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["Thinking...".to_string()],
                description: "jcode thinking state".to_string(),
            },
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["Baking...".to_string()],
                description: "jcode baking state (processing)".to_string(),
            },
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["Streaming...".to_string()],
                description: "jcode streaming response".to_string(),
            },
            DetectionRule {
                state: AgentState::Blocked,
                patterns: vec!["❯".to_string(), "Yes".to_string(), "No".to_string()],
                description: "jcode permission prompt".to_string(),
            },
            DetectionRule {
                state: AgentState::Blocked,
                patterns: vec!["Do you want to proceed?".to_string()],
                description: "jcode confirmation prompt".to_string(),
            },
            DetectionRule {
                state: AgentState::Idle,
                patterns: vec!["❯".to_string()],
                description: "jcode input prompt (idle)".to_string(),
            },
        ],
    }
}

/// Build the ForgeCode screen manifest.
pub fn forgecode_manifest() -> ScreenManifest {
    ScreenManifest {
        agent: "forgecode".to_string(),
        version: "1".to_string(),
        rules: vec![
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["●".to_string()],
                description: "forgecode spinner active (working)".to_string(),
            },
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["Thinking...".to_string()],
                description: "forgecode thinking state".to_string(),
            },
            DetectionRule {
                state: AgentState::Working,
                patterns: vec!["Baking...".to_string()],
                description: "forgecode baking state".to_string(),
            },
            DetectionRule {
                state: AgentState::Blocked,
                patterns: vec!["Do you want to proceed?".to_string()],
                description: "forgecode confirmation prompt".to_string(),
            },
            DetectionRule {
                state: AgentState::Blocked,
                patterns: vec!["❯".to_string(), "Yes".to_string(), "No".to_string()],
                description: "forgecode permission prompt".to_string(),
            },
            DetectionRule {
                state: AgentState::Idle,
                patterns: vec!["❯".to_string()],
                description: "forgecode input prompt (idle)".to_string(),
            },
        ],
    }
}

/// Write a manifest TOML file to the given path.
pub fn write_manifest(
    manifest: &ScreenManifest,
    path: &std::path::Path,
) -> std::io::Result<()> {
    std::fs::write(path, manifest.to_toml())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn jcode_manifest_generates_valid_toml() {
        let manifest = jcode_manifest();
        let toml = manifest.to_toml();
        assert!(toml.contains("agent = \"jcode\""));
        assert!(toml.contains("version = \"1\""));
        assert!(toml.contains("state = \"working\""));
        assert!(toml.contains("state = \"idle\""));
        assert!(toml.contains("state = \"blocked\""));
        // Verify it's valid TOML
        let parsed: toml::Value = toml::from_str(&toml)
            .expect("manifest should be valid TOML");
        assert_eq!(
            parsed.get("agent").and_then(|v| v.as_str()),
            Some("jcode")
        );
    }

    #[test]
    fn forgecode_manifest_generates_valid_toml() {
        let manifest = forgecode_manifest();
        let toml = manifest.to_toml();
        assert!(toml.contains("agent = \"forgecode\""));
        let parsed: toml::Value = toml::from_str(&toml)
            .expect("manifest should be valid TOML");
        assert_eq!(
            parsed.get("agent").and_then(|v| v.as_str()),
            Some("forgecode")
        );
    }
}
