//! HERDR plugin manifest generation for jcode and ForgeCode.
//!
//! Produces a `herdr-plugin.toml` that registers jcode (and ForgeCode)
//! as a *local* HERDR plugin so users don't have to clone
//! `leonardoacosta/herdr-jcode` or `capt-marbles/jcode-integration`.
//! Both of those external plugins wrap the same in-process
//! [`crate::reporter::HerdrReporter`] this crate provides — shipping
//! the manifest directly avoids external-plugin fork proliferation.
//!
//! # Schema
//!
//! The schema mirrors the TOML emitted by the upstream community
//! plugins (`leonardoacosta.herdr-jcode`, `capt-marbles.jcode-integration`)
//! so the local plugin is indistinguishable from a downloaded one:
//!
//! ```toml
//! id = "kooshapari.jcode"
//! name = "Jcode HERDR integration"
//! version = "0.1.0"
//! min_herdr_version = "0.8.0"
//! description = "..."
//! platforms = ["linux", "macos"]
//!
//! [[agents]]
//! kind = "jcode"
//! manifest = "~/.config/herdr/agent-detection/jcode.toml"
//!
//! [[actions]]
//! id = "install"
//! title = "Install Jcode lifecycle reporting"
//! command = ["jcode", "herdr", "install"]
//! ```
//!
//! HERDR itself is Unix-only (it relies on a Unix-domain socket and a
//! `cfg!(unix)` build). On Windows the install hint points users to
//! WSL2 + a Herdr WSL build.

mod platforms;

#[cfg(test)]
mod tests;

/// Plugin identifier for the local jcode HERDR integration.
pub const JCODE_PLUGIN_ID: &str = "kooshapari.jcode";

/// Plugin identifier for the local ForgeCode HERDR integration.
pub const FORGECODE_PLUGIN_ID: &str = "kooshapari.forgecode";

/// Minimum HERDR version this plugin supports.
pub const MIN_HERDR_VERSION: &str = "0.8.0";

/// A `[[agents]]` entry — associates an agent kind with its
/// screen-detection manifest path so HERDR's auto-detector can resolve
/// the rules for any pane that is running this agent.
#[derive(Debug, Clone)]
pub struct AgentEntry {
    /// Agent kind identifier (e.g. "jcode", "forgecode").
    pub kind: String,
    /// Path to the agent-detection manifest (relative or absolute).
    pub manifest: String,
}

/// A single `[[actions]]` entry — an action the user can run from the
/// HERDR palette for this plugin.
#[derive(Debug, Clone)]
pub struct PluginAction {
    /// Stable identifier (e.g. "install").
    pub id: String,
    /// Human-readable title (e.g. "Install Jcode lifecycle reporting").
    pub title: String,
    /// Optional longer description.
    pub description: Option<String>,
    /// Command + args as a TOML inline array.
    pub command: Vec<String>,
}

/// A complete HERDR plugin manifest.
#[derive(Debug, Clone)]
pub struct PluginManifest {
    /// Stable plugin identifier (e.g. "kooshapari.jcode").
    pub id: String,
    /// Human-readable plugin name.
    pub name: String,
    /// Plugin semantic version.
    pub version: String,
    /// Minimum HERDR version required.
    pub min_herdr_version: String,
    /// One-line description.
    pub description: String,
    /// Platforms this plugin supports ("linux", "macos", …).
    pub platforms: Vec<String>,
    /// Agent-kind entries this plugin registers.
    pub agents: Vec<AgentEntry>,
    /// User-invokable actions.
    pub actions: Vec<PluginAction>,
}

impl PluginManifest {
    /// Render the plugin as a `herdr-plugin.toml` document.
    pub fn to_toml(&self) -> String {
        let mut out = String::new();

        // Header comments so the file is human-readable when opened
        // directly in $EDITOR.
        out.push_str(&format!(
            "# HERDR plugin manifest for {}\n\
             # Auto-generated by jcode-herdr\n",
            self.id
        ));

        // Scalars. Use serde_json for escaping — same semantics as the
        // toml crate uses for basic strings (so no need to manually
        // escape \n, \t, etc.).
        out.push_str(&format!(
            "id = {}\n\
             name = {}\n\
             version = {}\n\
             min_herdr_version = {}\n\
             description = {}\n",
            quote_str(&self.id),
            quote_str(&self.name),
            quote_str(&self.version),
            quote_str(&self.min_herdr_version),
            quote_str(&self.description),
        ));

        // Platforms array.
        out.push_str("platforms = [");
        for (i, p) in self.platforms.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&quote_str(p));
        }
        out.push_str("]\n\n");

        // Agents array.
        for agent in &self.agents {
            out.push_str("[[agents]]\n");
            out.push_str(&format!("kind = {}\n", quote_str(&agent.kind)));
            out.push_str(&format!("manifest = {}\n", quote_str(&agent.manifest)));
            out.push('\n');
        }

        // Actions array.
        for action in &self.actions {
            out.push_str("[[actions]]\n");
            out.push_str(&format!("id = {}\n", quote_str(&action.id)));
            out.push_str(&format!("title = {}\n", quote_str(&action.title)));
            if let Some(desc) = &action.description {
                out.push_str(&format!("description = {}\n", quote_str(desc)));
            }
            out.push_str("command = [");
            for (i, c) in action.command.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(&quote_str(c));
            }
            out.push_str("]\n\n");
        }

        out
    }
}

/// Wrap a string in TOML basic-string quotes with escaping for `\`, `"`,
/// and control characters. This produces output that round-trips
/// cleanly through `toml::from_str` and matches what `toml::to_string`
/// would emit.
fn quote_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04X}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Build the local jcode plugin manifest.
pub fn jcode_plugin() -> PluginManifest {
    let install_hint = platforms::install_command_hint();
    let mut description =
        String::from("Reports Jcode working/idle lifecycle state plus session identity. ");
    description.push_str("In-process HerdrReporter (no external plugin required).");
    if cfg!(windows) {
        description.push(' ');
        description.push_str(&platforms::windows_install_hint());
    }

    PluginManifest {
        id: JCODE_PLUGIN_ID.to_string(),
        name: "Jcode HERDR integration".to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        min_herdr_version: MIN_HERDR_VERSION.to_string(),
        description,
        platforms: platforms::platforms_for_host(),
        agents: vec![AgentEntry {
            kind: "jcode".to_string(),
            manifest: "~/.config/herdr/agent-detection/jcode.toml".to_string(),
        }],
        actions: vec![
            PluginAction {
                id: "install".to_string(),
                title: "Install Jcode lifecycle reporting".to_string(),
                description: Some(
                    "Write screen-detection manifests and re-emit this plugin entry.".to_string(),
                ),
                command: install_hint.clone(),
            },
            PluginAction {
                id: "status".to_string(),
                title: "Show Jcode HERDR status".to_string(),
                description: Some(
                    "Print HERDR env vars, pane id, and reporter activity.".to_string(),
                ),
                command: platforms::replace_cmd(install_hint.clone(), "herdr status"),
            },
            PluginAction {
                id: "doctor".to_string(),
                title: "Diagnose Jcode HERDR integration".to_string(),
                description: Some(
                    "Run cargo-check + cargo-test on the jcode-herdr crate.".to_string(),
                ),
                command: vec![
                    "sh".to_string(),
                    "-c".to_string(),
                    "cd \"$HERDR_PLUGIN_ROOT/../../../../\" && \
                     cargo check -p jcode-herdr && cargo test -p jcode-herdr"
                        .to_string(),
                ],
            },
        ],
    }
}

/// Build the local ForgeCode plugin manifest.
pub fn forgecode_plugin() -> PluginManifest {
    let install_hint = platforms::install_command_hint();
    let mut description =
        String::from("Reports ForgeCode working/idle lifecycle state plus session identity. ");
    description.push_str("In-process HerdrReporter (no external plugin required).");
    if cfg!(windows) {
        description.push(' ');
        description.push_str(&platforms::windows_install_hint());
    }

    PluginManifest {
        id: FORGECODE_PLUGIN_ID.to_string(),
        name: "ForgeCode HERDR integration".to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        min_herdr_version: MIN_HERDR_VERSION.to_string(),
        description,
        platforms: platforms::platforms_for_host(),
        agents: vec![AgentEntry {
            kind: "forgecode".to_string(),
            manifest: "~/.config/herdr/agent-detection/forgecode.toml".to_string(),
        }],
        actions: vec![
            PluginAction {
                id: "install".to_string(),
                title: "Install ForgeCode lifecycle reporting".to_string(),
                description: Some("Write the ForgeCode screen-detection manifest.".to_string()),
                command: install_hint.clone(),
            },
            PluginAction {
                id: "status".to_string(),
                title: "Show ForgeCode HERDR status".to_string(),
                description: Some(
                    "Print HERDR env vars, pane id, and reporter activity.".to_string(),
                ),
                command: platforms::replace_cmd(install_hint, "herdr status"),
            },
        ],
    }
}

/// Write a plugin manifest to the given path. Convenience wrapper that
/// creates parent directories.
pub fn write_plugin(manifest: &PluginManifest, path: &std::path::Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, manifest.to_toml())
}
