#!/bin/sh
# Install HERDR screen manifest for ForgeCode
# POSIX-compatible — no bashisms

set -e

MANIFEST_DIR="$HOME/.config/herdr/agent-detection"
MANIFEST_FILE="$MANIFEST_DIR/forgecode.toml"

# Check if HERDR is installed
if ! command -v herdr >/dev/null 2>&1 && [ ! -d "$HOME/.config/herdr" ]; then
    echo "Error: HERDR is not installed (no herdr binary or ~/.config/herdr/ found)." >&2
    exit 1
fi

# Create agent-detection directory if needed
mkdir -p "$MANIFEST_DIR"

# Write the TOML manifest
cat > "$MANIFEST_FILE" <<'EOF'
# HERDR screen manifest for ForgeCode
# Auto-generated by herdr-install-forgecode.sh

[[rules]]
state = "working"
patterns = ["●", "Thinking...", "Baking..."]

[[rules]]
state = "blocked"
patterns = ["Do you want to proceed?", "Yes/No"]

[[rules]]
state = "idle"
patterns = ["❯"]
EOF

if [ $? -eq 0 ]; then
    echo "Success: ForgeCode manifest installed to $MANIFEST_FILE"
else
    echo "Error: Failed to write manifest to $MANIFEST_FILE" >&2
    exit 1
fi
